spring:
  application:
    name: è®ºå›ç³»ç»Ÿ
  output:
    ansi:
      enabled: always # é…ç½®è¾“å‡ºæ•ˆæœ

  datasource:
    url: jdbc:mysql://localhost:3306/forum_db?useSSL=false&serverTimezone=UTC
    username: root
    password: Xrw2001724..
    driver-class-name: com.mysql.cj.jdbc.Driver # æ•°æ®åº“è¿æ¥é©±åŠ¨

    # ğŸ‘‡ æ˜ç¡®æŒ‡å®š Druid
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 27070 # è‡ªå®šä¹‰æœåŠ¡å™¨ç«¯å£

# é…ç½®mybatisåˆ°å“ªé‡Œå»æ‰¾ä½ çš„ Mapper XML æ–‡ä»¶ï¼ˆSQL æ˜ å°„æ–‡ä»¶ï¼‰
mybatis:
  mapper-locations: classpath:mapper/**/*.xml # classpathè¡¨ç¤ºè·¯å¾„æ˜¯ä»ç¼–è¯‘åçš„ç±»è·¯å¾„ï¼ˆtarget/classesï¼‰ä¸‹æŸ¥æ‰¾
                                              # **/*.xml é€šé…ç¬¦ï¼Œè¡¨ç¤ºå¯ä»¥é€’å½’æŸ¥æ‰¾ä»»æ„å±‚çº§çš„ .xml æ–‡ä»¶

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
  level:
    root: info
    com.honortech.forum_system: debug
  file:
    path: E:/forum_system/log_dir


springdoc:
  api-docs:
    enabled: true           # æ˜¯å¦å¯ç”¨ API æ–‡æ¡£ï¼ˆç”Ÿäº§ç¯å¢ƒå¯å…³é—­ï¼‰
    path: /v3/api-docs      # æ–‡æ¡£è®¿é—®è·¯å¾„ï¼Œå¯è‡ªå®šä¹‰
  swagger-ui:
    enabled: true           # æ˜¯å¦å¯ç”¨ Swagger UI
    path: /swagger-ui.html  # Swagger UI è®¿é—®è·¯å¾„
    display-request-duration: true  # æ˜¾ç¤ºè¯·æ±‚è€—æ—¶
    tags-sorter: alpha      # æ ‡ç­¾æŒ‰å­—æ¯æ’åº
    operations-sorter: alpha # æ¥å£æŒ‰å­—æ¯æ’åº
  packages-to-scan: com.honortech.forum_system.controller  # æŒ‡å®šæ‰«æçš„ controller åŒ…

